use super::{
    ASR_ARCHIVE_MAX_BYTES, ASR_EVENT_NAME, ASR_EXTRACT_MAX_BYTES, ASR_MODEL_ARCHIVE_BYTES,
    ASR_MODEL_DIR_NAME, ASR_MODEL_SHA256, ASR_MODEL_URL, ASR_MODEL_VERSION,
    ASR_REQUIRED_FREE_BYTES,
};
use bzip2::read::BzDecoder;
use fs2::available_space;
use futures_util::StreamExt;
use once_cell::sync::Lazy;
use parking_lot::Mutex;
use reqwest::{redirect::Policy, Client, Response, StatusCode};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs::{self, File, OpenOptions};
use std::io::{self, Read, Write};
use std::path::{Component, Path, PathBuf};
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};
use std::time::Duration;
use tauri::{AppHandle, Emitter};
use url::Url;
use uuid::Uuid;

const ASR_ARCHIVE_ROOT_NAME: &str = "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17";

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct AsrModelRequest {
    /// Kept as a wrapper for a stable IPC contract.  The current model is
    /// fixed and therefore has no user-controlled fields.
    #[serde(default)]
    pub force: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum AsrModelState {
    Missing,
    Downloading,
    Installed,
    Incomplete,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AsrModelStatus {
    pub state: AsrModelState,
    pub installed: bool,
    pub version: String,
    pub model_bytes: u64,
    pub total_bytes: u64,
    pub languages: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AsrModelProgress {
    pub stage: String,
    pub progress: u8,
    pub downloaded: u64,
    pub total: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct InstallMarker {
    version: String,
    archive_sha256: String,
}

static ACTIVE_DOWNLOAD: Lazy<Mutex<Option<Arc<AtomicBool>>>> = Lazy::new(|| Mutex::new(None));

pub fn model_status(app: &AppHandle) -> Result<AsrModelStatus, String> {
    let root = model_root(app)?;
    let target = root.join(ASR_MODEL_DIR_NAME);
    let (model, tokens, marker) = required_files(&target);
    let active = ACTIVE_DOWNLOAD.lock().is_some();
    let state = if active {
        AsrModelState::Downloading
    } else if model.is_some() && tokens.is_some() && marker {
        AsrModelState::Installed
    } else if target.exists() {
        AsrModelState::Incomplete
    } else {
        AsrModelState::Missing
    };
    let model_bytes = model
        .as_ref()
        .and_then(|path| fs::metadata(path).ok())
        .map(|meta| meta.len())
        .unwrap_or(0);
    Ok(AsrModelStatus {
        installed: state == AsrModelState::Installed,
        state,
        version: ASR_MODEL_VERSION.to_string(),
        model_bytes,
        total_bytes: ASR_MODEL_ARCHIVE_BYTES,
        languages: ["auto", "zh", "en", "ja", "ko", "yue"]
            .into_iter()
            .map(str::to_string)
            .collect(),
    })
}

/// Return the global, non-profile model directory.  The returned path is
/// generated by the backend and is never accepted from IPC input.
pub fn model_directory(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(model_root(app)?.join(ASR_MODEL_DIR_NAME))
}

pub async fn download_model(
    app: AppHandle,
    request: AsrModelRequest,
) -> Result<AsrModelStatus, String> {
    if !valid_sha256(ASR_MODEL_SHA256) {
        emit(&app, "failed", 0, 0, ASR_MODEL_ARCHIVE_BYTES);
        return Err("ASR_MODEL_HASH_UNAVAILABLE: 官方模型校验值尚未确认，已阻止下载".to_string());
    }
    if !request.force {
        if let Ok(status) = model_status(&app) {
            if status.installed {
                return Ok(status);
            }
        }
    }
    let cancel = {
        let mut active = ACTIVE_DOWNLOAD.lock();
        if active.is_some() {
            return Err("ASR_MODEL_DOWNLOAD_BUSY: 模型正在下载中".to_string());
        }
        let token = Arc::new(AtomicBool::new(false));
        *active = Some(token.clone());
        token
    };
    let result = download_model_inner(app.clone(), cancel.clone()).await;
    ACTIVE_DOWNLOAD.lock().take();
    result
}

pub fn cancel_model_download() -> Result<(), String> {
    if let Some(token) = ACTIVE_DOWNLOAD.lock().as_ref() {
        token.store(true, Ordering::Release);
    }
    Ok(())
}

pub fn delete_model(app: &AppHandle) -> Result<AsrModelStatus, String> {
    if ACTIVE_DOWNLOAD.lock().is_some() {
        return Err("ASR_MODEL_DOWNLOAD_BUSY: 下载期间不能删除模型".to_string());
    }
    let root = model_root(app)?;
    let target = root.join(ASR_MODEL_DIR_NAME);
    if !is_descendant(&target, &root) {
        return Err("ASR_MODEL_DELETE_REFUSED: 模型目录不安全".to_string());
    }
    if target.exists() {
        fs::remove_dir_all(&target)
            .map_err(|_| "ASR_MODEL_DELETE_FAILED: 删除模型失败".to_string())?;
    }
    model_status(app)
}

async fn download_model_inner(
    app: AppHandle,
    cancel: Arc<AtomicBool>,
) -> Result<AsrModelStatus, String> {
    let root = model_root(&app)?;
    fs::create_dir_all(&root)
        .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 无法创建模型目录".to_string())?;
    let parent = root.parent().unwrap_or(&root);
    if available_space(parent).unwrap_or(0) < ASR_REQUIRED_FREE_BYTES {
        emit(&app, "failed", 0, 0, ASR_MODEL_ARCHIVE_BYTES);
        return Err("ASR_MODEL_DISK_SPACE_LOW: 可用磁盘空间不足".to_string());
    }
    emit(&app, "checking", 0, 0, ASR_MODEL_ARCHIVE_BYTES);
    let client = Client::builder()
        .redirect(Policy::none())
        .connect_timeout(Duration::from_secs(20))
        .timeout(Duration::from_secs(120))
        .build()
        .map_err(|_| "ASR_MODEL_CLIENT_FAILED: 无法创建下载客户端".to_string())?;
    let response = fetch_official_archive(&client).await?;
    let total = response.content_length().unwrap_or(ASR_MODEL_ARCHIVE_BYTES);
    if total == 0 || total > ASR_ARCHIVE_MAX_BYTES || total != ASR_MODEL_ARCHIVE_BYTES {
        return Err("ASR_MODEL_SIZE_INVALID: 官方模型归档大小异常".to_string());
    }
    let temp = root.join(format!(".download-{}.part", Uuid::new_v4()));
    let digest = match stream_archive(&app, response, &temp, &cancel, total).await {
        Ok(digest) => digest,
        Err(error) => {
            let _ = fs::remove_file(&temp);
            emit(&app, "failed", 0, 0, total);
            return Err(error);
        }
    };
    if digest != ASR_MODEL_SHA256.to_ascii_lowercase() {
        let _ = fs::remove_file(&temp);
        emit(&app, "failed", 0, 0, total);
        return Err("ASR_MODEL_HASH_MISMATCH: 模型归档完整性校验失败".to_string());
    }
    emit(&app, "verifying", 70, total, total);
    let staging = root.join(format!(".install-{}", Uuid::new_v4()));
    fs::create_dir_all(&staging)
        .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 无法创建临时目录".to_string())?;
    let extract_result = extract_archive(&temp, &staging);
    let _ = fs::remove_file(&temp);
    if let Err(error) = extract_result {
        let _ = fs::remove_dir_all(&staging);
        emit(&app, "failed", 0, total, total);
        return Err(error);
    }
    emit(&app, "extracting", 80, total, total);
    let extracted = staging.join(ASR_MODEL_DIR_NAME);
    if !verify_required_files(&extracted) {
        let _ = fs::remove_dir_all(&staging);
        emit(&app, "failed", 0, total, total);
        return Err(
            "ASR_MODEL_CONTENT_INVALID: 模型缺少 model.int8.onnx 或 tokens.txt".to_string(),
        );
    }
    fs::write(
        extracted.join(".integrity.json"),
        serde_json::to_vec(&InstallMarker {
            version: ASR_MODEL_VERSION.to_string(),
            archive_sha256: digest,
        })
        .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 无法写入完整性标记".to_string())?,
    )
    .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 无法写入完整性标记".to_string())?;
    let target = root.join(ASR_MODEL_DIR_NAME);
    let incoming = root.join(format!(".incoming-{}", Uuid::new_v4()));
    fs::rename(&extracted, &incoming)
        .map_err(|_| "ASR_MODEL_INSTALL_FAILED: 无法准备模型安装".to_string())?;
    let _ = fs::remove_dir_all(&staging);
    emit(&app, "installing", 95, total, total);
    atomic_install(&root, &target, &incoming)?;
    emit(&app, "completed", 100, total, total);
    model_status(&app)
}

async fn stream_archive(
    app: &AppHandle,
    response: Response,
    temp: &Path,
    cancel: &AtomicBool,
    total: u64,
) -> Result<String, String> {
    let mut stream = response.bytes_stream();
    let mut file = OpenOptions::new()
        .create_new(true)
        .write(true)
        .open(temp)
        .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 无法创建临时归档".to_string())?;
    let mut hasher = Sha256::new();
    let mut downloaded = 0u64;
    while let Some(chunk) = stream.next().await {
        if cancel.load(Ordering::Acquire) {
            let _ = fs::remove_file(temp);
            emit(app, "cancelled", 0, downloaded, total);
            return Err("ASR_MODEL_DOWNLOAD_CANCELLED: 模型下载已取消".to_string());
        }
        let chunk = chunk.map_err(|_| "ASR_MODEL_DOWNLOAD_FAILED: 下载数据读取失败".to_string())?;
        downloaded = downloaded.saturating_add(chunk.len() as u64);
        if downloaded > ASR_ARCHIVE_MAX_BYTES || downloaded > total {
            return Err("ASR_MODEL_SIZE_INVALID: 下载数据超过限制".to_string());
        }
        file.write_all(&chunk)
            .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 写入临时归档失败".to_string())?;
        hasher.update(&chunk);
        let progress = ((downloaded.saturating_mul(65) / total.max(1)) as u8).min(65);
        emit(app, "downloading", progress, downloaded, total);
    }
    file.flush()
        .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 刷新临时归档失败".to_string())?;
    if downloaded != total {
        return Err("ASR_MODEL_SIZE_INVALID: 下载数据大小不完整".to_string());
    }
    Ok(format!("{:x}", hasher.finalize()))
}

async fn fetch_official_archive(client: &Client) -> Result<Response, String> {
    let mut url = Url::parse(ASR_MODEL_URL).expect("fixed ASR URL");
    for _ in 0..3 {
        let response = client
            .get(url.clone())
            .header("accept", "application/octet-stream")
            .send()
            .await
            .map_err(|_| "ASR_MODEL_NETWORK_FAILED: 无法连接官方模型服务".to_string())?;
        if response.status().is_redirection() {
            let location = response
                .headers()
                .get(reqwest::header::LOCATION)
                .and_then(|value| value.to_str().ok())
                .ok_or_else(|| "ASR_MODEL_REDIRECT_INVALID: 官方下载重定向无效".to_string())?;
            url = url
                .join(location)
                .map_err(|_| "ASR_MODEL_REDIRECT_INVALID: 官方下载重定向无效".to_string())?;
            if !trusted_github_url(&url) {
                return Err("ASR_MODEL_REDIRECT_REFUSED: 下载重定向目标不受信任".to_string());
            }
            continue;
        }
        if response.status() != StatusCode::OK {
            return Err(format!(
                "ASR_MODEL_HTTP_FAILED: 官方模型服务返回 {}",
                response.status().as_u16()
            ));
        }
        return Ok(response);
    }
    Err("ASR_MODEL_REDIRECT_LIMIT: 官方下载重定向次数过多".to_string())
}

fn trusted_github_url(url: &Url) -> bool {
    url.scheme() == "https"
        && matches!(
            url.host_str(),
            Some("github.com")
                | Some("release-assets.githubusercontent.com")
                | Some("objects.githubusercontent.com")
                | Some("github-releases.githubusercontent.com")
        )
}

fn extract_archive(archive: &Path, staging: &Path) -> Result<(), String> {
    let file = File::open(archive)
        .map_err(|_| "ASR_MODEL_ARCHIVE_INVALID: 无法读取模型归档".to_string())?;
    let decoder = BzDecoder::new(file);
    let mut archive = tar::Archive::new(decoder);
    let mut extracted_bytes = 0u64;
    let entries = archive
        .entries()
        .map_err(|_| "ASR_MODEL_ARCHIVE_INVALID: 模型归档格式无效".to_string())?;
    for item in entries {
        let mut entry =
            item.map_err(|_| "ASR_MODEL_ARCHIVE_INVALID: 无法读取模型归档条目".to_string())?;
        let relative = safe_archive_path(
            &entry
                .path()
                .map_err(|_| "ASR_MODEL_ARCHIVE_INVALID: 模型路径无效".to_string())?,
        )?;
        let destination = staging.join(&relative);
        if !is_descendant(&destination, staging) {
            return Err("ASR_MODEL_ARCHIVE_PATH_INVALID: 模型归档路径越界".to_string());
        }
        let kind = entry.header().entry_type();
        if kind.is_dir() {
            fs::create_dir_all(&destination)
                .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 无法解包模型目录".to_string())?;
        } else if kind.is_file() {
            if let Some(parent) = destination.parent() {
                fs::create_dir_all(parent)
                    .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 无法解包模型目录".to_string())?;
            }
            let mut output = OpenOptions::new()
                .create_new(true)
                .write(true)
                .open(&destination)
                .map_err(|_| "ASR_MODEL_STORAGE_FAILED: 无法写入模型文件".to_string())?;
            let limit = ASR_EXTRACT_MAX_BYTES
                .saturating_sub(extracted_bytes)
                .saturating_add(1);
            let copied = io::copy(&mut entry.by_ref().take(limit), &mut output)
                .map_err(|_| "ASR_MODEL_ARCHIVE_INVALID: 解包模型文件失败".to_string())?;
            extracted_bytes = extracted_bytes.saturating_add(copied);
            if extracted_bytes > ASR_EXTRACT_MAX_BYTES {
                return Err("ASR_MODEL_SIZE_INVALID: 解包模型超过限制".to_string());
            }
        } else {
            return Err("ASR_MODEL_ARCHIVE_PATH_INVALID: 拒绝链接或特殊归档条目".to_string());
        }
    }
    Ok(())
}

fn safe_archive_path(path: &Path) -> Result<PathBuf, String> {
    let mut components = path.components();
    match components.next() {
        Some(Component::Normal(name)) if name == ASR_ARCHIVE_ROOT_NAME => {}
        _ => return Err("ASR_MODEL_ARCHIVE_PATH_INVALID: 模型归档根目录无效".to_string()),
    }
    let mut safe = PathBuf::from(ASR_MODEL_DIR_NAME);
    for component in components {
        match component {
            Component::Normal(name) => safe.push(name),
            _ => return Err("ASR_MODEL_ARCHIVE_PATH_INVALID: 模型归档路径越界".to_string()),
        }
    }
    Ok(safe)
}

fn atomic_install(root: &Path, target: &Path, incoming: &Path) -> Result<(), String> {
    if !is_descendant(target, root) || !is_descendant(incoming, root) {
        return Err("ASR_MODEL_INSTALL_FAILED: 模型安装路径不安全".to_string());
    }
    let backup = root.join(format!(".backup-{}", Uuid::new_v4()));
    let had_old = target.exists();
    if had_old {
        fs::rename(target, &backup)
            .map_err(|_| "ASR_MODEL_INSTALL_FAILED: 无法替换旧模型".to_string())?;
    }
    if let Err(error) = fs::rename(incoming, target) {
        if had_old {
            let _ = fs::rename(&backup, target);
        }
        return Err(format!(
            "ASR_MODEL_INSTALL_FAILED: 无法完成模型安装 ({error})"
        ));
    }
    if had_old {
        let _ = fs::remove_dir_all(backup);
    }
    Ok(())
}

fn model_root(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(crate::config::Config::data_root_dir(app)?.join("asr"))
}

fn required_files(target: &Path) -> (Option<PathBuf>, Option<PathBuf>, bool) {
    let model = target.join("model.int8.onnx");
    let tokens = target.join("tokens.txt");
    let marker = target.join(".integrity.json");
    let model_ok = fs::metadata(&model)
        .map(|meta| meta.is_file() && meta.len() > 1_048_576)
        .unwrap_or(false);
    let tokens_ok = fs::metadata(&tokens)
        .map(|meta| meta.is_file() && meta.len() > 0 && meta.len() < 10 * 1024 * 1024)
        .unwrap_or(false);
    let marker_ok = fs::read_to_string(marker)
        .ok()
        .and_then(|value| serde_json::from_str::<InstallMarker>(&value).ok())
        .is_some_and(|value| {
            value.version == ASR_MODEL_VERSION && value.archive_sha256 == ASR_MODEL_SHA256
        });
    (
        model_ok.then_some(model),
        tokens_ok.then_some(tokens),
        marker_ok,
    )
}

fn verify_required_files(target: &Path) -> bool {
    let (model, tokens, _) = required_files_without_marker(target);
    model && tokens
}

fn required_files_without_marker(target: &Path) -> (bool, bool, bool) {
    let model = target.join("model.int8.onnx");
    let tokens = target.join("tokens.txt");
    (
        fs::metadata(model)
            .map(|meta| meta.is_file() && meta.len() > 1_048_576)
            .unwrap_or(false),
        fs::metadata(tokens)
            .map(|meta| meta.is_file() && meta.len() > 0 && meta.len() < 10 * 1024 * 1024)
            .unwrap_or(false),
        true,
    )
}

fn valid_sha256(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn is_descendant(path: &Path, root: &Path) -> bool {
    path.strip_prefix(root).is_ok() && path != root
}

fn emit(app: &AppHandle, stage: &str, progress: u8, downloaded: u64, total: u64) {
    let _ = app.emit(
        ASR_EVENT_NAME,
        AsrModelProgress {
            stage: stage.to_string(),
            progress,
            downloaded,
            total,
        },
    );
}

#[cfg(test)]
mod tests {
    use super::{safe_archive_path, trusted_github_url, valid_sha256};
    use std::path::Path;
    use url::Url;

    #[test]
    fn rejects_archive_traversal_and_unexpected_roots() {
        assert!(safe_archive_path(Path::new(
            "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17/model.int8.onnx"
        ))
        .is_ok());
        assert!(safe_archive_path(Path::new(
            "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17/../escape"
        ))
        .is_err());
        assert!(safe_archive_path(Path::new("other/model.int8.onnx")).is_err());
        assert!(safe_archive_path(Path::new("/sense-voice/model.int8.onnx")).is_err());
    }

    #[test]
    fn redirects_only_accept_known_github_asset_hosts() {
        assert!(trusted_github_url(
            &Url::parse("https://release-assets.githubusercontent.com/a").unwrap()
        ));
        assert!(!trusted_github_url(
            &Url::parse("https://example.com/a").unwrap()
        ));
        assert!(!trusted_github_url(
            &Url::parse("http://github.com/a").unwrap()
        ));
    }

    #[test]
    fn hash_gate_accepts_only_a_complete_hex_digest() {
        assert!(valid_sha256(
            "7d1efa2138a65b0b488df37f8b89e3d91a60676e416f515b952358d83dfd347e"
        ));
        assert!(!valid_sha256("__PENDING_OFFICIAL_SHA256__"));
        assert!(valid_sha256(&"a".repeat(64)));
    }
}
